apiVersion: v1
kind: Namespace
metadata:
  name: students-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-students-api
  namespace: students-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: students-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: students-api
    spec:
      containers:
      - image: 993619579/students-api
        imagePullPolicy: Always
        name: students-api
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-students-api
  namespace: students-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: students-api
    app.kubernetes.io/name: mysql