apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
      - image: mysql
        imagePullPolicy: Always
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "12345678"
          - name: MYSQL_PASSWORD
            value: "12345678"
          - name: MYSQL_USER
            value: "students"
          - name: MYSQL_DATABASE
            value: "testing"
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app.kubernetes.io/name: mysql